version: '3'
services:
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:  
      - REDIS_HOSTS=redis:redis
    ports:
      - 8081:8081
  
  producer:
    image: icaro/redis-producer
    depends_on:
     - redis
    environment:
      - SPRING_REDIS_HOST=redis
    ports:
     - 8080:8080

  consumer:
    image: icaro/redis-consumer
    depends_on:
     - redis
    environment:
      - SPRING_REDIS_HOST=redis
    ports:
     - 8082-8090:8082
